
#!/bin/bash
#
# Title: ampbase (v2)
# Author(s):  timekills
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # CORE (MANDATORY) DO NOT CHANGE ###########################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'youtubedl'
        intport: '17442'
        extport: '17442'
        image: 'tzahi12345/youtubedl-material:nightly'

    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # EXTRA FUNCTIONS REQUIRED BY THE ROLE #####################################

    # LABELS #### KEEPS BOTTOM CLEAN ###########################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/youtubedl-material'
          - '/mnt/unionfs:/mnt/unionfs/'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'

    # MAIN SCRIPT ##############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
